"""End-to-end tests for the Orszag-Tang W3C PROV example mapping."""

from __future__ import annotations

import base64
from pathlib import Path

import numpy as np
from adios2.stream import Stream
from hpc_campaign import Manager
from hpc_campaign.prov_mapping import HPC
from prov.model import ProvActivity, ProvDerivation, ProvEntity, ProvGeneration

from scripts.adios_derived_variables import processFile as create_derived_dataset
from scripts.adios_stats import processFile as create_statistics_dataset
from scripts.mhd_provenance import (
    VisualizationProvenanceRecorder,
    active_document,
    record_campaign_provenance,
)
from scripts.add_scalar_fields_to_campaign import add_scalar_field_sequence
from scripts.render_adios_visualizations_to_campaign import (
    add_visualization,
    visualization_sequence_name,
)

# A valid one-pixel PNG keeps the visualization test independent of rendering
# details while exercising the real image-sequence and provenance APIs.
TINY_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
)


def _write_prefixed_source(path: Path) -> None:
    """Write one self-describing MHD step using code-specific names."""
    y, x = np.mgrid[0:3, 0:4]
    fields = {
        "sim_rho": 1.0 + x + y,
        "sim_pressure": 2.0 + x * y,
        "sim_bx": x.astype(np.float64),
        "sim_by": y.astype(np.float64),
    }
    with Stream(str(path), "w") as stream:
        stream.begin_step()
        for name, values in fields.items():
            data = np.asarray(values, dtype=np.float64)
            stream.write(name, data, data.shape, [0, 0], data.shape)
        stream.end_step()


def _register_datasets(manager: Manager, root: Path, paths: list[Path]) -> None:
    """Register payloads using the run-relative names consumed by PROV."""
    for path in paths:
        manager.data(str(path), name=path.relative_to(root).as_posix())


def _logical_entities(document) -> list[ProvEntity]:
    return [
        record
        for record in document.get_records(ProvEntity)
        if HPC["LogicalVariable"] in record.get_asserted_types()
    ]


def test_ingest_records_runs_derived_fields_and_statistics(tmp_path: Path) -> None:
    """The graph must preserve run generation and exact multi-input lineage."""
    run_dir = tmp_path / "run-001"
    run_dir.mkdir()
    source = run_dir / "output.bp"
    derived = run_dir / "analysis.bp"
    statistics = run_dir / "output_stats.bp"
    _write_prefixed_source(source)
    create_derived_dataset(source, derived)
    create_statistics_dataset(source, statistics)

    manager = Manager(archive="mhd.aca", campaign_store=str(tmp_path))
    manager.open(create=True, truncate=True)
    try:
        _register_datasets(manager, tmp_path, [source, derived, statistics])
        index = record_campaign_provenance(manager, [source, derived, statistics], tmp_path)
        document = active_document(manager)

        pressure = index.by_definition[("run-001", "pressure")].reference
        magnetic_x = index.by_definition[("run-001", "magnetic_field_x")].reference
        magnetic_y = index.by_definition[("run-001", "magnetic_field_y")].reference
        divergence = index.by_definition[("run-001", "magnetic_field_divergence")].reference
        pressure_mean = index.by_definition[("run-001", "pressure_mean")].reference

        # Source variables are generated by the SimulationRun Activity.
        pressure_generation = [
            record
            for record in document.get_records(ProvGeneration)
            if record.args[0] == pressure
        ]
        assert len(pressure_generation) == 1
        assert pressure_generation[0].args[1] == index.runs["run-001"]

        # div(B) is derived from both vector components. This also exercises
        # campaign relationship roles containing underscores.
        divergence_parents = {
            record.args[1]
            for record in document.get_records(ProvDerivation)
            if record.args[0] == divergence
        }
        assert divergence_parents == {magnetic_x, magnetic_y}

        # Statistics remain first-class logical variables with their own
        # Activity instead of being unstructured metadata on the source.
        mean_parents = {
            record.args[1]
            for record in document.get_records(ProvDerivation)
            if record.args[0] == pressure_mean
        }
        assert mean_parents == {pressure}
        mean_entity = next(record for record in _logical_entities(document) if record.identifier == pressure_mean)
        assert mean_entity.get_attribute(HPC["units"]) == {"normalized pressure"}

        qoi_activities = [
            record
            for record in document.get_records(ProvActivity)
            if HPC["QuantityOfInterest"] in record.get_asserted_types()
        ]
        assert qoi_activities
    finally:
        manager.close()


def test_visualization_records_all_inputs_and_sequence_manifest(tmp_path: Path) -> None:
    """A streamline sequence must trace to vector and background variables."""
    run_dir = tmp_path / "run-001"
    run_dir.mkdir()
    source = run_dir / "output.bp"
    _write_prefixed_source(source)

    manager = Manager(archive="mhd.aca", campaign_store=str(tmp_path))
    manager.open(create=True, truncate=True)
    try:
        _register_datasets(manager, tmp_path, [source])
        index = record_campaign_provenance(manager, [source], tmp_path)

        semantic_variables = {
            "streamline_by": ("sim_bx", "sim_by"),
            "color_by": "sim_pressure",
        }
        sequence_short_name = "magnetic_streamlines"
        add_visualization(
            manager=manager,
            dataset_name="run-001/output.bp",
            variable=sequence_short_name,
            vis_type="streamlines",
            name=sequence_short_name,
            steps=[0],
            images=[TINY_PNG],
            replace=False,
            thumbnail_step=0,
            semantic_kwargs=semantic_variables,
        )
        sequence_name = visualization_sequence_name("run-001/output.bp", sequence_short_name)
        recorder = VisualizationProvenanceRecorder(
            manager,
            Path(__file__).parents[1] / "scripts" / "render_adios_visualizations_to_campaign.py",
        )
        output = recorder.record(
            source_dataset="run-001/output.bp",
            sequence_name=sequence_name,
            vis_type="streamlines",
            semantic_kwargs=semantic_variables,
            steps=[0],
            rendering_parameters={"colormap": "viridis"},
        )

        # Scalar heatmaps use color_by rather than a generic primary role; the
        # output must still inherit pressure's scientific identity.
        add_visualization(
            manager=manager,
            dataset_name="run-001/output.bp",
            variable="sim_pressure",
            vis_type="heatmap",
            name="pressure_heatmap",
            steps=[0],
            images=[TINY_PNG],
            replace=False,
            thumbnail_step=0,
            semantic_kwargs={"color_by": "sim_pressure"},
        )
        pressure_output = recorder.record(
            source_dataset="run-001/output.bp",
            sequence_name=visualization_sequence_name("run-001/output.bp", "pressure_heatmap"),
            vis_type="heatmap",
            semantic_kwargs={"color_by": "sim_pressure"},
            steps=[0],
            rendering_parameters={"colormap": "viridis"},
        )
        document = active_document(manager)

        expected_inputs = {
            index.by_definition[("run-001", "magnetic_field_x")].reference,
            index.by_definition[("run-001", "magnetic_field_y")].reference,
            index.by_definition[("run-001", "pressure")].reference,
        }
        actual_inputs = {
            record.args[1]
            for record in document.get_records(ProvDerivation)
            if record.args[0] == output
        }
        assert actual_inputs == expected_inputs

        output_entity = next(record for record in _logical_entities(document) if record.identifier == output)
        assert output_entity.get_attribute(HPC["variableDefinition"]) == {"magnetic_field_visualization"}
        manifest_name = next(iter(output_entity.get_attribute(HPC["datasetName"])))
        assert str(manifest_name).startswith("run-001/provenance/visualizations/")

        pressure_entity = next(
            record for record in _logical_entities(document) if record.identifier == pressure_output
        )
        assert pressure_entity.get_attribute(HPC["variableDefinition"]) == {"pressure_visualization"}
    finally:
        manager.close()


def test_scalar_field_sequence_records_items_and_provenance(tmp_path: Path) -> None:
    """A scalar-field sequence must register raw fields and source lineage."""
    run_dir = tmp_path / "run-001"
    run_dir.mkdir()
    source = run_dir / "output.bp"
    _write_prefixed_source(source)

    manager = Manager(archive="mhd.aca", campaign_store=str(tmp_path))
    manager.open(create=True, truncate=True)
    try:
        _register_datasets(manager, tmp_path, [source])
        index = record_campaign_provenance(manager, [source], tmp_path)
        field = np.arange(12, dtype=np.float64).reshape(3, 4)

        add_scalar_field_sequence(
            manager,
            dataset_name="run-001/output.bp",
            variable="sim_pressure",
            vis_type="heatmap",
            name="pressure_scalar_field",
            steps=[0],
            arrays=[field],
            replace=False,
            dtype="float32",
        )
        sequence_name = visualization_sequence_name(
            "run-001/output.bp",
            "pressure_scalar_field",
        )
        recorder = VisualizationProvenanceRecorder(
            manager,
            Path(__file__).parents[1] / "scripts" / "add_scalar_fields_to_campaign.py",
        )
        output = recorder.record(
            source_dataset="run-001/output.bp",
            sequence_name=sequence_name,
            vis_type="heatmap",
            semantic_kwargs={"color_by": "sim_pressure"},
            steps=[0],
            rendering_parameters={"scalar_fields": True, "dtype": "float32"},
        )

        info_data = manager.info(list_replicas=True, list_files=True)
        sequence_info = next(
            sequence
            for sequence in info_data.visualization_sequences.values()
            if sequence.name == sequence_name
        )
        assert sequence_info.items[0].item_type == "SCALAR_FIELD"
        scalar_dataset = next(
            dataset
            for dataset in info_data.datasets.values()
            if dataset.name == sequence_info.items[0].dataset_name
        )
        assert scalar_dataset.file_format == "SCALAR_FIELD"
        assert scalar_dataset.metadata["shape"] == [3, 4]
        assert scalar_dataset.metadata["dtype"] == "float32"

        document = active_document(manager)
        pressure_entity = next(record for record in _logical_entities(document) if record.identifier == output)
        assert pressure_entity.get_attribute(HPC["variableDefinition"]) == {"pressure_visualization"}
        expected_pressure = index.by_definition[("run-001", "pressure")].reference
        actual_inputs = {
            record.args[1]
            for record in document.get_records(ProvDerivation)
            if record.args[0] == output
        }
        assert actual_inputs == {expected_pressure}
    finally:
        manager.close()
